### ISSUE TITLE
Tabulation

### ISSUE THREAD

**Issue by UNdedss** [SenticodeCourses/IvanHramyka#10]
https://github.com/SenticodeCourses/IvanHramyka/blob/0e9a867a9fa095aaf1d6ef5d714190711ef3d690/IndraAndCo.Management.Library/Project.cs#L22

tabulation for object initializer

**Comment by IvanHramyka** [comment]
Т.е. вот так?!
       Tasks = Enumerable.Range(0, randomTask.Next(1,10))
                .Select(i => new Task()
                { SpecialtyForTask = (Specialty) randomTask.Next(Enum.GetNames(typeof(Specialty)).Length) })
                .ToList();
